version: '3'
services:
  express:
    image: hhwang927/nodejs
    tty: true
    container_name: express
    ports:
      - "4000:4000"
    volumes:
      - "./usf:/root/usf"
    command: bash -c "
      cd /root/usf/express_backend
      && npm install
      && npm run dev"